"""
Multilingual Support System
Translations for all form labels and UI elements
"""

TRANSLATIONS = {
    'en': {
        'page_title': 'Healthcare Recommendation System',
        'login': 'Login',
        'home': 'Home',
        'select_language': 'Select Language',
        'select_body_part': 'Select Body Part',
        'specialization': 'Specialization',
        'disease': 'Disease',
        'symptom': 'Symptoms',
        'age': 'Age',
        'fees': 'Consultation Fees (Rs)',
        'location': 'Location',
        'doctor_name': 'Doctor Name (Optional)',
        'feedback': 'Describe Your Experience (Optional)',
        'search': 'Find Best Doctors',
        'clear': 'Clear',
        'queries': 'Medical Queries',
        'ask_query': 'Ask a Medical Question',
        'your_query': 'Your Question',
        'submit': 'Submit',
        'top_doctors': 'Top Doctors',
        'doctor_rating': 'Rating',
        'consultation_fee': 'Fee',
        'experience': 'Experience',
        'speciality': 'Speciality',
        'view_profile': 'View Profile',
        'patient_feedback': 'Patient Feedback',
        'sentiment': 'Overall Sentiment',
        'issue_detected': 'Main Issue',
        'match_score': 'Match Score',
        'confidence': 'Confidence',
        'no_results': 'No doctors found. Try different criteria.',
        'error': 'Error',
        'loading': 'Loading...',
        'heart': 'Heart',
        'liver': 'Liver',
        'lungs': 'Lungs',
        'brain': 'Brain / Neuro',
        'kidney': 'Kidney',
        'eye': 'Eye',
        'bones': 'Bones',
        'ent': 'ENT',
        'skin': 'Skin & Hair',
        'teeth': 'Teeth',
        'general': 'General',
        'positive': 'Positive',
        'negative': 'Negative',
        'neutral': 'Neutral',
        'results_title': 'Personalized doctor recommendations',
        'results_disease_label': 'Disease:',
        'results_symptom_label': 'Symptom:',
        'results_fee': 'Fee:',
        'results_location': 'Location:',
        'results_average_rating': 'Rating:',
        'results_sentiment': 'Sentiment:',
        'results_review_category': 'Review Category:',
        'results_specialization': 'Specialization:',
        'results_department': 'Department:',
        'results_feedback_sample': 'Feedback sample:',
        'results_recommendation_score': 'Recommendation Score:',
        'results_view_doctor_profile': 'View Doctor Profile',
        'results_ask_medical_query': 'Ask a Medical Query',
        'results_back_home': 'Back to Home',
        'results_no_matching': 'No matching doctors were found. Try changing the fee or location filters.',
    },
    
    'ta': {  # Tamil
        'page_title': 'சுகாதார பரிந்துரை முறைமை',
        'login': 'உள்நுழைய',
        'home': 'வீடு',
        'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
        'select_body_part': 'உடல் பாகத்தைத் தேர்ந்தெடுக்கவும்',
        'specialization': 'சிறப்புத்துறை',
        'disease': 'நோய்',
        'symptom': 'அறிகுறிகள்',
        'age': 'வயது',
        'fees': 'ஆலோசனை கட்டணம் (Rs)',
        'location': 'இடம்',
        'doctor_name': 'மருத்துவர் பெயர் (விருப்பமாக)',
        'feedback': 'உங்கள் அனுபவத்தை விவரிக்கவும் (விருப்பமாக)',
        'search': 'சிறந்த மருத்துவர்களை கண்டுபிடி',
        'clear': 'அழி',
        'queries': 'மருத்துவ கேள்விகள்',
        'ask_query': 'மருத்துவ கேள்விஐ கேளுங்கள்',
        'your_query': 'உங்கள் கேள்வி',
        'submit': 'சமர்ப்பி',
        'top_doctors': 'சிறந்த மருத்துவர்கள்',
        'doctor_rating': 'மதிப்பீடு',
        'consultation_fee': 'கட்டணம்',
        'experience': 'அனுபவம்',
        'speciality': 'சிறப்புத்துறை',
        'view_profile': 'சுயவிவரத்தைப் பார்க்கவும்',
        'patient_feedback': 'நோயாளி கருத்து',
        'sentiment': 'ஒட்டுமொத்த உணர்வு',
        'issue_detected': 'முக்கிய சிக்கல்',
        'match_score': 'பொருத்தம் மதிப்பீடு',
        'confidence': 'நம்பிக்கை',
        'no_results': 'மருத்துவர்கள் கிடைக்கவில்லை. வேறு அளவுகோல்களை முயற்சிக்கவும்.',
        'error': 'பிழை',
        'loading': 'ஏற்றுதல்...',
        'heart': 'இதயம்',
        'liver': 'கல்லீரல்',
        'lungs': 'நுரையீரல்',
        'brain': 'மூளை / நரம்பு',
        'kidney': 'சிறுநீரகம்',
        'eye': 'கண்',
        'bones': 'எலும்புகள்',
        'ent': 'ENT',
        'skin': 'त्वचा & बाल',
        'teeth': 'பற்கள்',
        'general': 'பொது',
        'positive': 'ইতিবাচক',
        'negative': 'नেतिबाचक',
        'neutral': 'निरपेक्ष',
        'results_title': 'ব্যক্তিগতকৃত ডাক्तर সুপारिश',
        'results_disease_label': 'நோய்:',
        'results_symptom_label': 'அறிकுறி:',
        'results_fee': 'कीमत:',
        'results_location': 'स्थान:',
        'results_average_rating': 'मूल्यांकन:',
        'results_sentiment': 'अनुभूति:',
        'results_review_category': 'समीक्षा श्रेणी:',
        'results_specialization': 'विशेषता:',
        'results_department': 'विभाग:',
        'results_feedback_sample': 'प्रतिक्रिया नमूना:',
        'results_recommendation_score': 'सुझाव स्कोर:',
        'results_view_doctor_profile': 'डॉक्टर प्रोफाइल देखें',
        'results_ask_medical_query': 'चिकित्सा प्रश्न पूछें',
        'results_back_home': 'घर जाएं',
        'results_no_matching': 'कोई मेल नहीं खाने वाले डॉक्टर नहीं मिले। शुल्क या स्थान को बदलने का प्रयास करें।',
    },
    
    'hi': {  # Hindi
        'page_title': 'स्वास्थ्य सेवा सिफारिश प्रणाली',
        'login': 'लॉगिन',
        'home': 'होम',
        'select_language': 'भाषा चुनें',
        'select_body_part': 'शरीर के अंग को चुनें',
        'specialization': 'विशेषज्ञता',
        'disease': 'बीमारी',
        'symptom': 'लक्षण',
        'age': 'आयु',
        'fees': 'परामर्श शुल्क (Rs)',
        'location': 'स्थान',
        'doctor_name': 'डॉक्टर का नाम (वैकल्पिक)',
        'feedback': 'अपना अनुभव बताएं (वैकल्पिक)',
        'search': 'सर्वोत्तम डॉक्टर खोजें',
        'clear': 'साफ करें',
        'queries': 'चिकित्सा प्रश्न',
        'ask_query': 'चिकित्सा प्रश्न पूछें',
        'your_query': 'आपका प्रश्न',
        'submit': 'जमा करें',
        'top_doctors': 'शीर्ष डॉक्टर',
        'doctor_rating': 'रेटिंग',
        'consultation_fee': 'शुल्क',
        'experience': 'अनुभव',
        'speciality': 'विशेषज्ञता',
        'view_profile': 'प्रोफ़ाइल देखें',
        'patient_feedback': 'रोगी प्रतिक्रिया',
        'sentiment': 'समग्र भावना',
        'issue_detected': 'मुख्य समस्या',
        'match_score': 'मैच स्कोर',
        'confidence': 'आत्मविश्वास',
        'no_results': 'कोई डॉक्टर नहीं मिला। अन्य मानदंड आजमाएं।',
        'error': 'त्रुटि',
        'loading': 'लोड हो रहा है...',
        'heart': 'दिल',
        'liver': 'यकृत',
        'lungs': 'फेफड़े',
        'brain': 'मस्तिष्क / तंत्रिका',
        'kidney': 'गुर्दा',
        'eye': 'आँख',
        'bones': 'हड्डियाँ',
        'ent': 'ENT',
        'skin': 'त्वचा और बाल',
        'teeth': 'दाँत',
        'general': 'सामान्य',
        'positive': 'सकारात्मक',
        'negative': 'नकारात्मक',
        'neutral': 'तटस्थ',
    },
    
    'te': {  # Telugu
        'page_title': 'ఆరోగ్య సిఫారిష్ సిస్టమ్',
        'login': 'లాగిన్',
        'home': 'హోమ్',
        'select_language': 'భాషను ఎంచుకోండి',
        'select_body_part': 'శరీర భాగాన్ని ఎంచుకోండి',
        'specialization': 'విశేషత',
        'disease': 'వ్యాధి',
        'symptom': 'లక్షణాలు',
        'age': 'వయస్సు',
        'fees': 'సంప్రదింపు ఫీ (Rs)',
        'location': 'స్థానం',
        'doctor_name': 'డాక్టర్ పేరు (ఐచ్ఛికం)',
        'feedback': 'మీ అভిజ్ఞతను వివరించండి (ఐచ్ఛికం)',
        'search': 'ఉత్తమ డాక్టర్లను కనుగొనండి',
        'clear': 'క్లియర్ చేయండి',
        'queries': 'వైద్య ప్రశ్నలు',
        'ask_query': 'వైద్య ప్రశ్న అడగండి',
        'your_query': 'మీ ప్రశ్న',
        'submit': 'సమర్పించండి',
        'top_doctors': 'టాప్ డాక్టర్లు',
        'doctor_rating': 'రేటింగ్',
        'consultation_fee': 'ఫీ',
        'experience': 'అనుభవం',
        'speciality': 'విశేషత',
        'view_profile': 'ప్రొఫైల్ చూడండి',
        'patient_feedback': 'రోగి ప్రతిస్పందన',
        'sentiment': 'సమగ్ర భావన',
        'issue_detected': 'ప్రధాన సమస్య',
        'match_score': 'మ్యాచ్ స్కోర్',
        'confidence': 'విశ్వాసం',
        'no_results': 'ఎటువంటి డాక్టర్లు కనుగొనబడలేదు. వేరే ప్రమాణాలను చేయండి.',
        'error': 'లోపం',
        'loading': 'లోడ్ చేస్తుంది...',
        'heart': 'హృదయం',
        'liver': 'కాలేయం',
        'lungs': 'ఊపిరితిత్తులు',
        'brain': 'మెదము / నరం',
        'kidney': 'మూత్రపిండం',
        'eye': 'కన్ను',
        'bones': 'ఎముకలు',
        'ent': 'ENT',
        'skin': 'త్వచ & చుట్టుకొలత',
        'teeth': 'పళ్ళు',
        'general': 'సాధారణ',
        'positive': 'సానుకూల',
        'negative': 'ప్రతికూల',
        'neutral': 'తటస్థ',
    },
    
    'kn': {  # Kannada
        'page_title': 'ಆರೋಗ್ಯ ಶಿಫಾರಸು ವ್ಯವಸ್ಥೆ',
        'login': 'ಲಾಗಿನ್',
        'home': 'ಮುಖ್ಯಪುಟ',
        'select_language': 'ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
        'select_body_part': 'ದೇಹದ ಭಾಗವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
        'specialization': 'ವಿಶೇಷತೆ',
        'disease': 'ರೋಗ',
        'symptom': 'ಲಕ್ಷಣಗಳು',
        'age': 'ಶಿಶುವಿನ ವಯಸ್ಸು',
        'fees': 'ಸಲಹೆ ಶುಲ್ಕ (Rs)',
        'location': 'ಸ್ಥಾನ',
        'doctor_name': 'ವೈದ್ಯನ ಹೆಸರು (ಐಚ್ಛಿಕ)',
        'feedback': 'ನಿಮ್ಮ ಅನುಭವವನ್ನು ವರ್ಣಿಸಿ (ಐಚ್ಛಿಕ)',
        'search': 'ಉತ್ತಮ ವೈದ್ಯರನ್ನು ಹುಡುಕಿ',
        'clear': 'ತೆರವುಗೊಳಿಸಿ',
        'queries': 'ವೈದ್ಯಕೀಯ ಪ್ರಶ್ನೆಗಳು',
        'ask_query': 'ವೈದ್ಯಕೀಯ ಪ್ರಶ್ನೆ ಕೇಳಿ',
        'your_query': 'ನಿಮ್ಮ ಪ್ರಶ್ನೆ',
        'submit': 'ಸಲ್ಲಿಸಿ',
        'top_doctors': 'ಅಗ್ರ ವೈದ್ಯರು',
        'doctor_rating': 'ರೇಟಿಂಗ್',
        'consultation_fee': 'ಶುಲ್ಕ',
        'experience': 'ಅನುಭವ',
        'speciality': 'ವಿಶೇಷತೆ',
        'view_profile': 'ಪ್ರೊಫೈಲ್ ನೋಡಿ',
        'patient_feedback': 'ರೋಗಿ ಪ್ರತಿಕ್ರಿಯೆ',
        'sentiment': 'ಸಂಪೂರ್ಣ ಭಾವನೆ',
        'issue_detected': 'ಮುಖ್ಯ ಸಮಸ್ಯೆ',
        'match_score': 'ಮ್ಯಾಚ್ ಸ್ಕೋರ್',
        'confidence': 'ಆತ್ಮವಿಶ್ವಾಸ',
        'no_results': 'ವೈದ್ಯರು ಕಂಡುಬಂದಿಲ್ಲ. ವಿಭಿನ್ನ ಮಾನದಂಡಗಳನ್ನು ಪ್ರಯತ್ನಿಸಿ.',
        'error': 'ದೋಷ',
        'loading': 'ಲೋಡ್ ಮಾಡಿಸುತ್ತಿದೆ...',
        'heart': 'ಹೃದಯ',
        'liver': 'ಯಕೃತ್',
        'lungs': 'ಶ್ವಾಸಕೋಶ',
        'brain': 'ಮಿದುಳು / ಪ್ರಭಾವ',
        'kidney': 'ಮೂತ್ರಶಾಸನ',
        'eye': 'ಕಣ್ಣು',
        'bones': 'ಮೂಳೆಗಳು',
        'ent': 'ENT',
        'skin': 'ಚರ್ಮ ಮತ್ತು ಕೇಶ',
        'teeth': 'ಹಲ್ಲುಗಳು',
        'general': 'ಸಾಮಾನ್ಯ',
        'positive': 'ಧನಾತ್ಮಕ',
        'negative': 'ಋಣಾತ್ಮಕ',
        'neutral': 'ನಿರುದ್ಯೋಗ',
    }
}

def get_translation(language_code, key):
    """Get translated text for a key in specified language"""
    if language_code not in TRANSLATIONS:
        language_code = 'en'  # Default to English
    
    return TRANSLATIONS.get(language_code, {}).get(key, TRANSLATIONS['en'].get(key, key))

def get_all_translations(language_code):
    """Get all translations for a language"""
    if language_code not in TRANSLATIONS:
        language_code = 'en'
    return TRANSLATIONS[language_code]

# Language list
SUPPORTED_LANGUAGES = [
    {'code': 'en', 'name': 'English'},
    {'code': 'ta', 'name': 'Tamil'},
    {'code': 'hi', 'name': 'Hindi'},
    {'code': 'te', 'name': 'Telugu'},
    {'code': 'kn', 'name': 'Kannada'},
]
